### ISSUE TITLE
Package not recognized

### ISSUE THREAD

**Issue by NoaD** [EverythingMe/probe#1]
Running on Mac 10.10.4
Trying to run probe with 'python console.py --package com.myapp.android'
and it says "can't find com.myapp.android, is it installed?", I looked into the code and added some prints to try and figure out what isn't working, no luck so far.
If I run the command 'ps | grep com.myapp.android' manually on the terminal it successfully returns the app process.

thought maybe it's permissions issue, so I run it with 
'sudo -E python console.py --package com.myapp.android'
nothing changed

I did notice that when I start running the script it closes the app on my device
So, any help will be appreciated, and OBVIOUSLY thank you for sharing your code!

**Comment by NoaD** [comment]
ok, problem solved - I missed the part where you must specify the activity name

**Comment by rotemmiz** [comment]
Thanks for the feedback, I think I'm gonna add a default activity mechanism (the first activity with CATEGORY_LAUNCHER intent filter), it should cover about 90% of all use cases.
